### ISSUE TITLE
Color: TextView overlaps SeekBar

### ISSUE THREAD

**Issue by enricocid** [maxkeppeler/sheets#106]
**Describe the bug**
r, g, b texts overlap the seekbar

**Library Version:**
2.2.7

**To Reproduce**
1. Action 1
2. Action 2
3. Action 3

**Expected behavior**
Consider using material sliders + value label or use fixed size texts (i.e. add leading zeros, 005, 024...)

**Screenshots**
![gif_20220214_174939](https://user-images.githubusercontent.com/7274841/153909712-70b55a12-cab8-490e-b875-200b710211ce.gif)

**Affected Device(s):**
 - Xiaomi Mi A1 Android 10

**Additional context**
NA

**Comment by maxkeppeler** [comment]
Leading zeros don't look good imo. I just added a constraint barrier to the labels and values to fix it from the layout.

**Comment by enricocid** [comment]
Hi @maxkeppeler 
I can still reproduce the issue :)

1. Change alpha to values < 100
2. Change R slider to reproduce the issue
3. Set R slider to values < 100
4. Change G slider to reproduce the issue... and so on.
