### ISSUE TITLE
Localization: consider using platform resources

### ISSUE THREAD

**Issue by enricocid** [maxkeppeler/sheets#107]
**Is your feature request related to a problem? Please describe.**
Not a bug, just a suggestion.

I think You should consider using android.R.string.ok and android.R.string.cancel for positive/negative buttons so You don't have to deal with translations.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maxkeppeler** [comment]
You are right, I removed the existing sheets_ok and sheets_cancel strings and replaced with them with the android string resource. Probably didn't think of it at the beginning. Thanks!
