### ISSUE TITLE
Core module leaking colour attributes into consuming applications

### ISSUE THREAD

**Issue by wax911** [maxkeppeler/sheets#111]
**Describe the bug**

First off, epic project and thank you for all the hard work you've put in. I have a fairly simple yet major issue regarding colour resources leaking into the consuming client application. I have found a couple of colour resources:
- `colorPrimary`
- `colorPrimaryDark` 
- `colorAccent`

These are also common names for colour resources in the material design language which are currently conflicting with a `theme` artifact we consume throughout our applications for common theming styles. Generally I see most of the colour resources are prefixed `sheet*` so just curious as to why these three exist in the `core` module.

**Library Version:**
2.2.7

**To Reproduce**
1. Use any `artifact` into a project that uses similar colour resources from the library

**Expected behavior**
If possible, we could refrain from using material design color names in `resources`, I have found a what seems to be the potential culprit:
https://github.com/maxkeppeler/sheets/blob/e1dde5237b4cdce9599e76c601cdd4915eb71ca9/core/src/main/res/values/colors.xml#L20-L22

Typically libraries shouldn't leak resources like this unless it is intended.

**Screenshots**
Example of colours pulled in from libraries with-in the project
![image](https://user-images.githubusercontent.com/7859175/166460968-de753823-b347-4407-aa37-bc88dfef0bfc.png)

**Affected Device(s):**
 - `N/A`

**Additional context**
I have not done a comprehensive deep dive to see where these colours are being used, so hopefully we can start a discussion on that

**Comment by maxkeppeler** [comment]
Thanks for bringing this issue to me. After taking a look, it really seems like they are just leftovers and therefore superfluous resources. Sheets `core` module only uses the colors starting with `sheets...`.
