### ISSUE TITLE
Option customisation support

### ISSUE THREAD

**Issue by ItzNotABug** [maxkeppeler/sheets#114]
Currently, there is no support for customizing Option based items.
Example: a Font List, different colours depending on the index, etc.

**Describe the solution you'd like**
Support customizing the title & subtitle TextViews completely like:
```kotlin
// Option
Option(/* Existing constructor args */, titleCust: (TextView.() -> Unit)? = null, subTitleCust: (TextView.() -> Unit)? = null)

// Usage
Option(R.drawable.menu_icon, "Menu Item", titleCust = { /*...*/ }, subTitleCust = { /*...*/ })
```

**Comment by maxkeppeler** [comment]
I believe it's a specific requirement that not many need. Therefore, I do not want to add it to the lib. Feel free to fork it and add that change and use it in your project. Sorry!
