### ISSUE TITLE
Custom year range in CalendarSheet

### ISSUE THREAD

**Issue by martynyshyn** [maxkeppeler/sheets#122]
As I understand, CalendarSheet has only -N .. +N year range. 
How can set custom year range, as 0 .. 1, -2 .. 0 or similar?
What about ability to set min & max dates to select?
Thanks!

**Comment by maxkeppeler** [comment]
Sorry, that's currently not possible. It has less config options than [Sheets-Compose-Dialogs](https://github.com/maxkeppeler/sheets-compose-dialogs). Though I would love to add it, I simply lack the time to do so at the moment. I'm open to PR though!
