### ISSUE TITLE
Upgrade to material 3.

### ISSUE THREAD

**Issue by snehilrx** [maxkeppeler/sheets#126]
**Is your feature request related to a problem? Please describe.**
No, As my project uses material 3, the sheet ui feels consistent with the rest of the UI.

**Describe the solution you'd like**
I want this feature to be compatible with the themes generated from the mdc3 theme generator. As it provides a consistent theme between Compose and the XML styles.

**Comment by maxkeppeler** [comment]
Check out my Shees-Compose-Dialogs library for Jetpack Compose & Material 3. Modifying this lib to use MD3 would be a ton of time, which I unfortunately do not have. Does this lib work for you?
