### ISSUE TITLE
Bottom Sheet for loading/waiting view.

### ISSUE THREAD

**Issue by adarshpugalia** [maxkeppeler/sheets#13]
**Describe the solution you'd like**
A bottom sheet to indicate loading/processing. Ideally, there should be two modes, determinate progress (percentage progress) and indeterminate progress. The bottom sheet should also be able to specify a title and a message (progress, or any other message).

**Comment by MaxKeppeler** [comment]
Any thoughts about the design of this kind of progress bottom sheet? Basically like an InfoSheet, title, progress value if percentags alongside a progress bar? Perhaps optionally a cover image too?

**Comment by irvine752** [comment]
An optional cover image would be great. A few options could be one with a static image (with a possible URL or drawable ID), a lottie animation or simply nothing. This would be just like the InfoSheet with the addition of the info for progress

For the progress (determinate or indeterminate), I would think a ProgressBar would do the trick. It could be something along the lines of:
https://i.stack.imgur.com/PuC7J.gif


like along ofthe indeterminate case it could be a horizontal bar Pr

**Comment by MaxKeppeler** [comment]
With the next version, lottie & cover image is supported. I will work on such a type of sheet at a later point. If you need such a component quickly, you could easily create a custom sheet, while having all the functionality (e. g. cover image/ lottie animation.
