### ISSUE TITLE
InfoSheet Enhancements 

### ISSUE THREAD

**Issue by irvine752** [MaxKeppeler/sheets#15]
**Describe the solution you'd like**
Request to add more features to the InfoSheet:
1) InfoSheet with Lottie Animation, and text at the bottom
2) InfoSheet with an image (url source or drawable) at the top, and text at the bottom.

*Url sources cover dynamic pictures, and the drawable covers icons + other static pictures

**Comment by MaxKeppeler** [comment]
With text at the bottom, you mean the title below the cover image / Lottie animation?

**Comment by irvine752** [comment]
yep, having it below the cover image /Lottie animation would work well.

**Comment by MaxKeppeler** [comment]
Great to hear. Did you notice the 3 styles for the top view? 

I did not work on Lottie animations yet. 
I want to offer it as an add-on library, with which the cover image view is used to display Lottie animations and offering several more helper methods regarding that. I think it would bloat the default base library too much if it's by default included. First, I first have to figure out how I implement this though.

If you checked out the latest work for the next release, did you play around with the `style(SheetStyle)` available for every sheet? It displays the view as either a dialog or a bottom-sheet.

**Comment by MaxKeppeler** [comment]
You are correct with the note on the missing contrast. It's possible to specify the colors for the icon buttons, so if it's known that the image is bright, dark colors can be used for the icons for a better contrast. That's correct, I'm setting the src for the icon drawable. However, I'm using the background for a ripple drawable. 
When I have time, I will work on an option for the IconButtons to specify a background color, which will be seen as a round circle in the respective color behind the icon buttons!

**Comment by irvine752** [comment]
Yep, I love the stuff I have seen so far. The top views should be more than enough for all the use cases. The SheetStyle is great for options, but you might have to change the name of the project though. :)

The icon background color would be a great addition. Looking forward to the next release!

**Comment by MaxKeppeler** [comment]
I will, probably to just "Sheets". Ehm. Not sure when though, I would want to change the dependency names and general structure of the modules then too.
