### ISSUE TITLE
InputSheet Password

### ISSUE THREAD

**Issue by irvine752** [maxkeppeler/sheets#31]
Not sure if you have this planned already. I think also having a fingerprint option would be great. If the user places a finger on the fingerprint sensor, you could also give some feedback. A fingerprint icon with a green check mark for an approved print, and maybe a fingerprint icon with a red cross mark for anything unrecognized. 

You also need an InputSheet to register new user passwords/fingerprints.

**Comment by MaxKeppeler** [comment]
Great idea for another Input for the InputSheet. I will work on this feature in the future!

**Comment by irvine752** [comment]
An example would be:
https://github.com/rahulabrol/Android-Fingerprint

but this is only using an approved fingerprint already registered with the device.

**Comment by maxkeppeler** [comment]
I will not add this, a custom sheet can be created for this if needed.
