### ISSUE TITLE
TimeSheet zero values

### ISSUE THREAD

**Issue by torack272** [maxkeppeler/sheets#40]
I'm not sure if this is a bug or working as intended.
The TimeSheet  doesn't allow selecting zero seconds as a value. It used to work in version 1.0.6 by setting the min value to 0 when initializing the TimeSheet. In version 2.0.0 this workaround doesn't seem to work anymore.

**Comment by maxkeppeler** [comment]
Thanks for the issue. I actually accepted a PR for this. I just spend another thought on this - and it's definitely a bug. If a value of zero is not desired,  the `minTime(...)` method should be used to declare the minimum value.
