### ISSUE TITLE
Change dialog and bottomSheet width

### ISSUE THREAD

**Issue by firetrap** [maxkeppeler/sheets#42]
It's useful to have a builder parameter to customize the Dialog/BottomSheet width.
It's not visually appealing to have a full-width bottom sheet when on tablets with landscape orientation.

**Comment by firetrap** [comment]
I added a [PR](https://github.com/maxkeppeler/sheets/pull/43) with the changes

**Comment by maxkeppeler** [comment]
I've been quite busy, thanks for the PR. Useful addition.
