### ISSUE TITLE
Duplicate Value Merge Error

### ISSUE THREAD

**Issue by nicemak** [maxkeppeler/sheets#44]
**Describe the bug**
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource compilation failed
     C:\Users\Maki\.gradle\caches\transforms-2\files-2.1\2ccd1e7c841bb979159f85186e44dbc7\preference-1.1.1\res\values\values.xml:257:5-336:25: AAPT: error: duplicate value for resource 'attr/defaultValue' with config ''.
         
     C:\Users\Maki\.gradle\caches\transforms-2\files-2.1\2ccd1e7c841bb979159f85186e44dbc7\preference-1.1.1\res\values\values.xml:257:5-336:25: AAPT: error: resource previously defined here.

**Library Version:**
2.0.0

**Expected behavior**
Should Compile.

**Comment by nicemak** [comment]
@maxkeppeler sir any help?

**Comment by maxkeppeler** [comment]
I can't replicate this issue. So I guess an id is the same as another from your values file? Which would that be?

**Comment by nicemak** [comment]
C:\Users\BI.IT-010\.gradle\caches\transforms-2\files-2.1\2ccd1e7c841bb979159f85186e44dbc7\preference-1.1.1\res\values\values.xml:257:5-336:25: AAPT: error: duplicate value for resource 'attr/defaultValue' with config ''.

and

C:\Users\BI.IT-010\.gradle\caches\transforms-2\files-2.1\2ccd1e7c841bb979159f85186e44dbc7\preference-1.1.1\res\values\values.xml:257:5-336:25: AAPT: error: resource previously defined here.

on clicking on these errors, this file opens.

<declare-styleable name="Preference">
        
        <attr name="icon"/>
        <attr name="android:icon"/>
        
        <attr format="string" name="key"/>
        <attr name="android:key"/>
        
        <attr name="title"/>
        <attr name="android:title"/>
        
        <attr format="string" name="summary"/>
        <attr name="android:summary"/>
        
        <attr format="integer" name="order"/>
        <attr name="android:order"/>
        
        <attr format="string" name="fragment"/>
        <attr name="android:fragment"/>
        
        <attr name="layout"/>
        <attr name="android:layout"/>
        
        <attr format="reference" name="widgetLayout"/>
        <attr name="android:widgetLayout"/>
        
        <attr format="boolean" name="enabled"/>
        <attr name="android:enabled"/>
        
        <attr format="boolean" name="selectable"/>
        <attr name="android:selectable"/>
        
        <attr format="string" name="dependency"/>
        <attr name="android:dependency"/>
        
        <attr format="boolean" name="persistent"/>
        <attr name="android:persistent"/>
        
        <attr format="string|boolean|integer|reference|float" name="defaultValue"/>
        <attr name="android:defaultValue"/>
        
        <attr format="boolean" name="shouldDisableView"/>
        <attr name="android:shouldDisableView"/>

        
        <attr format="boolean" name="allowDividerAbove"/>

        
        <attr format="boolean" name="allowDividerBelow"/>

        
        <attr format="boolean" name="singleLineTitle"/>
        <attr name="android:singleLineTitle"/>

        
        <attr format="boolean" name="iconSpaceReserved"/>
        <attr name="android:iconSpaceReserved"/>

        
        <attr format="boolean" name="isPreferenceVisible"/>

        
        <attr format="boolean" name="enableCopying"/>
    </declare-styleable>

may be some other library is conflicting with your library resources.

**Comment by nicemak** [comment]
may be this dependency causing issue,

preference: "androidx.preference:preference-ktx:1.1.1"

which is present in your core library, may be some other library is also using this.

**Comment by maxkeppeler** [comment]
There's no attr with "defaultValue" in the values.xml. 
There's also no conflicting attrs, the sheet library's names start with "sheet...". 
Indeed, I use the preference library, so the fragment manager can be taken out of the context in the PreferenceFragmentCompat. 
I don't really know how to fix this for now - I will attempt to try some things out on the weekend.

**Comment by maxkeppeler** [comment]
Sorry, I can't replicate it and don't know how to continue with this issue you have. 
If you know anything else, let me know.

**Comment by nicemak** [comment]
Hi there!

i solved my issue by excluding preference library from your library, now its working wonderfully.

`implementation ('com.maxkeppeler.sheets:core:2.0.0') {
        exclude group: 'androidx.preference', module: 'preference-ktx'
    }
    implementation ('com.maxkeppeler.sheets:input:2.0.0') {
        exclude group: 'androidx.preference', module: 'preference-ktx'
    }`

**Comment by maxkeppeler** [comment]
Nice! However, I wonder how I can fix this on my end. I only need it in order to get the FragmentManager from the PreferenceContext. But it seems like the whole library is leaking?
