### ISSUE TITLE
There should be a drawable argument that is actually a drawable and not a resource

### ISSUE THREAD

**Issue by rosenpin** [maxkeppeler/sheets#45]
Currently the InfoSheet for example takes a resource for `drawable`, beside the fact that this is misleading, it limits the usage of this library.
In many cases drawables are loaded at run time and have no resource id.

I believe the default behavior should be to take an actual drawable as an argument, and add an option to supply a drawable resource as a different argument if you think it's necessary

**Comment by maxkeppeler** [comment]
I created this library for my personal needs at the beginning and always used drawable by id. 
But that's a basic thing and can be added! I will try to add it this weekend.

**Comment by rosenpin** [comment]
Nice!  
Thanks
