### ISSUE TITLE
Bintray shutting down

### ISSUE THREAD

**Issue by RussellBanks** [maxkeppeler/sheets#46]
This is just to let you know that [Bintray is shutting down in May](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) and this library seems to be hosted by Bintray.

**Comment by jackdevey** [comment]
YES!!

**Comment by maxkeppeler** [comment]
In the progress. I'm able to upload packages to Maven Central. 
However, I can't remove the jCenter repository though, because `org.jetbrains.trove4j` is hosted there.
[Jetbrains Issue](https://youtrack.jetbrains.com/issue/IDEA-261387#focus=Comments-27-4674463.0-0)

**Comment by maxkeppeler** [comment]
Sheets itself is now hosted on Maven Central, the repository jCenter will be removed after the library from JetBrains was migrated too.
