### ISSUE TITLE
Support android:supportsRtl="false"

### ISSUE THREAD

**Issue by braydentraas** [maxkeppeler/sheets#47]
**Describe the bug**
If RTL support is disabled application-wide, text alignment doesn't work properly (text is all left-aligned, `android:textAlignment="center"` is ignored)

This can be resolved by setting the `android:gravity="center"` attribute on SheetContent items (and probably others).

**Library Version:**
2.0.0

**To Reproduce**
1. Set `android:supportsRtl="false"` in Manifest.xml
2. Display an OptionsSheet grid

**Expected behavior**
Option label text should be centered.

**Comment by maxkeppeler** [comment]
Will look after this & fix it on the weekend, thanks for letting me know!
