### ISSUE TITLE
The time displayed is wrong with HH_MM formating

### ISSUE THREAD

**Issue by fivez** [maxkeppeler/sheets#48]
**Describe the bug**
When using the following code, the time displayed is incorrect :

```
TimeSheet().show(context) {
            title(title)
            currentTime(TimeUnit.HOURS.toSeconds(0).plus(TimeUnit.MINUTES.toSeconds(50)))
            format(TimeFormat.HH_MM)
            onPositive { durationTimeInSeconds: Long ->
                // Handle selected time
            }
            onNegative {
            }
        }
```

**Library Version:**
2.0.0

**To Reproduce**
1. By using the above displayed code, the time displayed is not 00h50m but 50h00m.

**Expected behavior**
1. By using the above displayed code, the time displayed would be 00h50m.

**Screenshots**
-

**Affected Device(s):**
-

**Additional context**
-

**Comment by fivez** [comment]
Thanks!

**Comment by maxkeppeler** [comment]
No problem, thanks for reporting - shouldn't have happened in the first place.
