### ISSUE TITLE
Unable to locate 2.1.3 version

### ISSUE THREAD

**Issue by ubarua123** [maxkeppeler/sheets#51]
```
Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/maxkeppeler/bottomsheets/core/2.1.3/core-2.1.3.pom
       - https://jcenter.bintray.com/com/maxkeppeler/bottomsheets/core/2.1.3/core-2.1.3.pom
       - https://repo.maven.apache.org/maven2/com/maxkeppeler/bottomsheets/core/2.1.3/core-2.1.3.pom
       - https://jitpack.io/com/maxkeppeler/bottomsheets/core/2.1.3/core-2.1.3.pom
       - https://dl.bintray.com/kotlin/kotlin-eap/com/maxkeppeler/bottomsheets/core/2.1.3/core-2.1.3.pom
       - https://plugins.gradle.org/m2/com/maxkeppeler/bottomsheets/core/2.1.3/core-2.1.3.pom

allProjects {
         repositories {
             google()
             jcenter()
             mavenCentral()
             dependencies { apply from: "$rootProject.rootDir/version-groups.gradle" }
             maven { url "https://jitpack.io" } // add this line
             maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
             maven { url "https://plugins.gradle.org/m2/" }
         }
}
```

Any more repos I am missing out 😀

**Comment by bartez** [comment]
Could you show your implementation in build.gradle for app? I found lib on maven central and link don't have _bottomsheets_.
Your url:
https://repo.maven.apache.org/maven2/com/maxkeppeler/**bottomsheets**/core/2.1.3/core-2.1.3.pom
Maven Central url:
https://repo1.maven.org/maven2/com/maxkeppeler/**sheets**/core/2.1.3/core-2.1.3.aar

**Comment by maxkeppeler** [comment]
The repo  ```mavenCentral()``` is correct. (Is the repository in the buildscript or allprojects?)

The package name was previously changed from `com.maxkeppeler.bottomsheets` to `com.maxkeppeler.sheets` to reflect the functionality that a component can be displayed dynamically as a bottom-sheet or a dialog.

The dependencies look like this now:
```implementation 'com.maxkeppeler.sheets:<module>:<latest-version>```
Are your dependencies correct?

Overview of the dependencies:
https://search.maven.org/search?q=com.maxkeppeler.sheets

Browse the artifacts here:
https://repo1.maven.org/maven2/com/maxkeppeler/sheets/

Make sure to use the latest version.

I remember I had the same issue until I cleaned caches etc. Afterwards it pulled the library from the correct url.

**Comment by ubarua123** [comment]
Thanks! Yes that was the issue. Didn't notice the package name change.
Another quick question: I want to the override the styles of the sheets. What is the parent style that I should extend in styles.xml? You have only specified the item attributes.

**Comment by maxkeppeler** [comment]
Great that it works now!

I use the parent style "Theme.MaterialComponents.DayNight.NoActionBar" in the sample. Either this style or a comparable style will do the job!
