### ISSUE TITLE
Quick actions for input has strange background

### ISSUE THREAD

**Issue by egorikftp** [maxkeppeler/sheets#52]
**Library Version:**
2.1.3

**To Reproduce**
1. Add `InputSheet` with `InputEditText`
2. Try to Paste some text

**Expected behavior**
Shadow and background actions should be correct.

**Video**

https://user-images.githubusercontent.com/16294951/111306790-b453a200-8669-11eb-8982-7866e89a2563.mp4

**Comment by maxkeppeler** [comment]
Thanks for the issue. I've noted it down because I noticed the same issue a week ago. I'm very busy right now. I hope I might be able to have some minutes this weekend for it, or the next, to fix it and release a new version!

**Comment by egorikftp** [comment]
@maxkeppeler I have checked the sample and found, that problem related to this attribute: **android:panelBackground**

This code snippet helps to solve the issue, maybe it will help solve the problem)

```
<style name="BottomSheet.Base.Light" parent="Theme.MaterialComponents.Light.BottomSheetDialog">
        <item name="android:panelBackground">@android:color/white</item>
        ....
    </style>
```

**Comment by maxkeppeler** [comment]
The attribute ```android:panelBackground``` didn't work for me. Due to the dialog and bottom-sheet styles I had to do a few more changes. It now works for me on my devices. Let me know if it works for you as well!
