### ISSUE TITLE
InputSheet Enhancements

### ISSUE THREAD

**Issue by irvine752** [maxkeppeler/sheets#56]
Could we also get the switch added to the InputSheet Options? Given that we already have radio buttons. I think we should have the switch as a standard option as well.

Another great idea would be adding some haptic feedback to the inputs, triggered upon input selection.

Let me know what you think.

**Comment by maxkeppeler** [comment]
Yes, I agree - I will add it. 

I'm not sure if this should be standard. Haptic feedback could be added whenever a value changes:
`changeListener { value -> haptic feedback here }`
