### ISSUE TITLE
Using the new Kotlin JVM IR with Sheets causes a compilation error

### ISSUE THREAD

**Issue by russellbanks** [maxkeppeler/sheets#57]
**Describe the bug**
The Kotlin team have rewritten the JVM compiler and this becomes default in Kotlin 1.5.0. However, attempting to use Sheets on an app that uses either the new IR on Kotlin 1.4.32 or Kotlin 1.5.0 where the new IR becomes the default compiler for Kotlin throws `TypeAliasDescriptor expected: class NegativeListener (not found)`.

Not knowing that Sheets was causing the issue, I commented on an issue on JetBrains YouTrack to which an employee responded showing the cause of the error. I have attached this under additional context. I have also attached two pipelines that show the thrown error on my project, the line in Sheets that causes the error and another issue that has more information about the problem in depth.

**Library Version:**
2.1.4

**To Reproduce**
1. Add `useIR = true` under `kotlinOptions{}` in Gradle or use Kotlin 1.5.0 where the new IR is default.

**Expected behavior**
The app should be able to compile with the new IR while using Sheets.

**Additional context**
- [Pipeline that shows the error on Kotlin 1.4.32 with the new IR](https://gitlab.com/bandev/buddha-quotes/-/jobs/1183040627)
- [Pipeline that shows the error on Kotlin 1.5.0-RC](https://gitlab.com/bandev/buddha-quotes/-/jobs/1183086170)
- [Issue on JetBrains YouTrack](https://youtrack.jetbrains.com/issue/KT-46000#focus=Comments-27-4843185.0-0)
- [Same error on YouTrack more in depth](https://youtrack.jetbrains.com/issue/KT-45308)
- [Identified String that causes the issue from Sheets](https://github.com/maxkeppeler/sheets/blob/5d2b1e950c61030d7c147eb641be1c95759db0ed/core/src/main/java/com/maxkeppeler/sheets/core/Sheet.kt#L42)

**Comment by maxkeppeler** [comment]
If they have rewritten the JVM compiler, where the code didn't lead to any issue, but now does with the new IR, isn't that something they have to work on? I'm not sure what I can do after checking out the links. 

I can not replicate it within the project running the sample with Kotlin 1.4.32 and the new IR. Can you replicate it there as well?

**Comment by russellbanks** [comment]
I've tried compiling the sample app with both Kotlin 1.5.0-RC and 1.4.32 with the new IR and this doesn't bring up an error, which is weird. I originally thought this would be something that would require a bit of migration but for now I'll close this issue and hope that the Kotlin team fix this soon. If it does require migration, I'll re-open the issue.

**Comment by russellbanks** [comment]
Fixed in Kotlin 1.5.20 with this [commit](https://github.com/JetBrains/kotlin/commit/6ca7b39f6a4f34e3eda3d23259734c7d318acbe6)
