### ISSUE TITLE
How to hide Positive & Negative buttons in InputSheet

### ISSUE THREAD

**Issue by Vijaykumarj** [maxkeppeler/sheets#68]
I can able to add Input radio buttons in the Input Sheet and but I want to hide the Positive & Negative buttons in InputSheet?

**Comment by maxkeppeler** [comment]
This is not possible right now. Other sheets have the method `displayButtons()` to show or hide the buttons view.
You want to only display the inputs and save & close automatically once all the inputs are valid?

**Comment by Vijaykumarj** [comment]
Thanks for the update, How to close automatically if all inputs are valid?

**Comment by maxkeppeler** [comment]
If you do not display the buttons, the only logical procedure would be to react automatically to it. Once are inputs are valid and set, it would automatically save the data and invoke the listeners and then dismiss the sheet. I will add this method to the InputSheet as well. (Perhaps on the weekend.) However, I don't think it's nice to handle that automatically, if the inputs are important - the user would like to have control when to finish and save the input data. Just for simple InputSheets it might come handy without a positive or negative button.

**Comment by Vijaykumarj** [comment]
thanks for your quick support and also considered my requirement.

**Comment by lilinormalgirl** [comment]
Hello][°
