### ISSUE TITLE
Set custom selected day on CalendarSheets

### ISSUE THREAD

**Issue by mena97villalobos** [maxkeppeler/sheets#69]
I need to set a custom date on CalendarSheets
Possible solution is to modify `private val today = LocalDate.now()` on CalendarSheets.kt and add a function to set the value to a custom date

**Comment by maxkeppeler** [comment]
There's a misunderstanding. The today date is supposed to be an indicator for the user to know the current day in the calendar view. The today indicated day and a day that is selected look different. The today-day is also still selectable.

Correct me if I'm wrong, but I think you wanted to have a method to pass the date or date range that was previously selected and display this state when the CalendarSheet was opened again. 

Following variables are used for this:

**For a single date selection:**
```private var selectedDate: LocalDate? = null```

**For a date range selection:**
```private var selectedDateStart: LocalDate? = null```
```private var selectedDateEnd: LocalDate? = null```

Out of your PR we could change it a bit to still make the Today-day indicator custom.
However the other variables need to be used for setting up default selected date or date range.

Let me know if I understood you and the situation correctly. (And sorry for not having react quicker.)

**Comment by mena97villalobos** [comment]
Hey! Sure, you got it correctly, I just wanted something like the today
value to set a "hint" of some sort instead of just selecting the value with
the values you mentioned. Anyway, I can work on changing the variables you
mentioned and creating something similar to the today indicator as
you suggested. Thanks for the heads up!
