### ISSUE TITLE
Text on Positive & Negative buttons in InputSheet not showing properly...

### ISSUE THREAD

**Issue by Surekha95** [maxkeppeler/sheets#75]
I'm unable set the styles for positive and negative buttons in input sheet.
![Sort](https://user-images.githubusercontent.com/24824197/123304503-a3ee7580-d53c-11eb-9374-3203030b7da9.png)

**Comment by maxkeppeler** [comment]
What kind of style are you using? The parent style should be ```Theme.MaterialComponents...```

**Comment by btraas** [comment]
I have the same with `Theme.MaterialComponents.Light.DarkActionBar.Bridge`. Switching to `Theme.MaterialComponents.Light.DarkActionBar` works fine

**Comment by maxkeppeler** [comment]
Didn't know it doesn't work with ```.Bridge``` as I've not used it before. Apologies.
