### ISSUE TITLE
Horizontal margins not showing with OptionSheet in Android 11

### ISSUE THREAD

**Issue by puntogris** [maxkeppeler/sheets#77]
**Describe the bug**
When using `OptionSheet` with `style(SheetStyle.DIALOG)` there are no horizontal margins in Android 11.

**Library Version:**
2.2.4

**Comment by maxkeppeler** [comment]
For whatever reason, the decoder view padding is 0 on Android 11. If that's the case, I can add a 16dp horizontal padding.
