### ISSUE TITLE
BottomSheet Theme Support

### ISSUE THREAD

**Issue by irvine752** [maxkeppeler/sheets#79]
For the Bottom Sheets, can we provide support for the navigation bar color updates?
I tried setting the color through:
 android:navigationBarColor or  window.navigationBarColor
The color still stays white. The issue is only highlighted when the overall theme is dark.

**Comment by maxkeppeler** [comment]
I will look into this and work on the library a little once I've a desk (I just moved into a new apartment), so it may still take a week or two until I can spend time on it, but I won't forget it.

**Comment by maxkeppeler** [comment]
Yes, it won't work this way. I just checked again, and it uses by default the predefined day and night mode background colors of a sheet. What you need is a way to change the navigation bar color to another color you can specify (and by default perhaps the attribute for the background of the sheet so they always match up.) So a programmatic way to set the NavigationBar color will work for you too?

**Comment by irvine752** [comment]
So it got a little better. The NavBar color changes to match the theme. My only concern now is the icon color for the NavBar. I'm setting this color for both (NavBar & Icon color) in a programmatic color. The Icon color should be inverted to see the Icons on the background. It works well for any Activity on my end, but once I bring up a sheet, the color is not inverted (ie white NavBar showing white Icons). For the Icon Color, I'm using this Activity extension below:

fun AppCompatActivity.setNavBarLightDark(is_light: Boolean) {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
        return
    }

    var flags = window.decorView.systemUiVisibility
    flags = if (is_light) {
        flags or View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR
    } else {
        flags and View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR.inv()
    }
    window.decorView.systemUiVisibility = flags
}

**Comment by maxkeppeler** [comment]
I'm just adding a method to change the NavBar color. Maybe I don't get it yet, but the NavBar color changes accordingly to the background color. 

The extension doesn't seem to work for me if I add it into the SheetFragment. It doesn't apply the state of a dark navigation bar.
