### ISSUE TITLE
Make it possible to add own view as animation / image

### ISSUE THREAD

**Issue by GraxCode** [maxkeppeler/sheets#85]
I have a View that displays an animated illustration. I would like to add it to a sheet.

**Comment by GraxCode** [comment]
Of course, I could make a custom sheet, but an easier solution would be to make InfoSheet extendable, or a function to add a view.

**Comment by maxkeppeler** [comment]
This is totally independent of the cover-image/ cover-animation view, am I right with that? 
Where/ how do you want to display this ImageView? What kind of animation view is that - Lottie?

**Comment by GraxCode** [comment]
It's a custom view with TextView, ImageView etc. 

I was looking for a way to add the view and found that it's possible to use InputCustom in InputDialog. Except, it doesn't function as an input, but more as some visual information between other text. I don't know if you want to make a better solution or keep it like that. Issue #86 emerged because of that, as my view now is slightly off to the right, as the parent view is padded.

**Comment by maxkeppeler** [comment]
Ah I understand. I will work on the other issue. I will add a method to add a custom view to the InfoSheet as well.

**Comment by maxkeppeler** [comment]
Custom views can now be used with the InfoSheet. They replace the default view. I close this and the other padding issue, as this fixes both.
