### ISSUE TITLE
InputCustom setting to not pad view

### ISSUE THREAD

**Issue by GraxCode** [maxkeppeler/sheets#86]
Currently, I have to do this:
```java
          inputCustom.view(myView, view -> null);
          rubbers.post(() -> ((ViewGroup) myView.getParent()).setPadding(0,0,0,0)); // workaround
          inputCustom.fullView(true);
```

There should be a setting to fix this.

**Comment by maxkeppeler** [comment]
Absolutely - will work on it soon. Sorry for the inconvenience!

**Comment by maxkeppeler** [comment]
I've to ask again. You basically want to get rid of the small 4dp padding at the top and bottom of the custom input item? May I know what are you trying to do? As I imagine it, it would look kinda off next to normal input items.
